#!/bin/bash

cd `dirname $(readlink -f $0)`
cd ..

OF=`pwd`

cd Difference

ORIGINS=$(find $OF/openFrameworks -type f -name *.origin)

for i in $ORIGINS; do
    diff -Naur $i `dirname $i`/`basename ${i%.*}` > $OF/Difference/`basename ${i%%.*}`.patch
done
