#!/bin/bash

OF_BRANCH=94ac319274
# See: https://github.com/openframeworks/openFrameworks/issues/2807
GLFW_BRANCH=7f4e947447
POCO_BRANCH=4923172241

download_progress()
{
    local flag=false c count cr=$'\r' nl=$'\n'
    while IFS='' read -d '' -rn 1 c
    do
        if $flag
        then
            printf '%c' "$c"
        else
            if [[ $c != $cr && $c != $nl ]]
            then
                count=0
            else
                ((count++))
                if ((count > 1))
                then
                    flag=true
                fi
            fi
        fi
    done
}

NORMAL=$(tput sgr0)
RED=$(tput setaf 1)
GREEN=$(tput setaf 2)

if [ -f $OF_BRANCH.zip ]
then
	echo "${GREEN}Using existing $OF_BRANCH.zip archive for openFrameworks.${NORMAL}"
else
    echo "${RED}Downloading $OF_BRANCH.zip archive for openFrameworks.${NORMAL}"
	wget --progress=bar:force https://github.com/openframeworks/openFrameworks/archive/$OF_BRANCH.zip 2>&1 | download_progress
fi

unzip -q $OF_BRANCH.zip

mv     openFrameworks-*/libs/openFrameworks .

rm -rf openFrameworks/.settings
rm     openFrameworks/.project
rm     openFrameworks/.cproject

patch -p1 < of_mingw_fix.patch
patch -p1 < of_glew_include_path_fix.patch
patch -p1 < of_freetype2_include_path_fix.patch
patch -p1 < of_drag_and_drop_feature.patch
patch -p1 < of_scroll_feature.patch
patch -p1 < of_audio_video_disable.patch

TESS=Dependencies/Libs/tess2
rm -rf $TESS
mkdir  $TESS
mv     openFrameworks-*/libs/tess2/include $TESS
mv     openFrameworks-*/libs/tess2/Sources $TESS

KISS=Dependencies/Libs/kiss
rm -rf $KISS
mkdir  $KISS
mv     openFrameworks-*/libs/kiss/include  $KISS
mv     openFrameworks-*/libs/kiss/src      $KISS

rm -rf openFrameworks-*

cd     Dependencies/Archive/glfw

if [ -f $GLFW_BRANCH.zip ]
then
	echo "${GREEN}Using existing $GLFW_BRANCH.zip archive for GLFW.${NORMAL}"
else
    echo "${RED}Downloading $GLFW_BRANCH.zip archive for GLFW.${NORMAL}"
	wget --progress=bar:force https://github.com/glfw/glfw/archive/$GLFW_BRANCH.zip 2>&1 | download_progress
fi

unzip -q $GLFW_BRANCH.zip

mv     glfw-* ../../Libs/glfw
rm -rf glfw-*

cd     ../../..

cd     Dependencies/Archive/poco

if [ -f $POCO_BRANCH.zip ]
then
	echo "${GREEN}Using existing $POCO_BRANCH.zip archive for POCO.${NORMAL}"
else
    echo "${RED}Downloading $POCO_BRANCH.zip archive for POCO.${NORMAL}"
	wget --progress=bar:force https://github.com/pocoproject/poco/archive/$POCO_BRANCH.zip 2>&1 | download_progress
fi

unzip -q $POCO_BRANCH.zip

mv     poco-* ../../Libs/poco
rm -rf poco-*

cd     ../../..

cd     Dependencies/Libs/poco

patch -p1 < ../../poco.patch

cd     ../../..

