#!/bin/bash

BRANCH=94ac319274
# See: https://github.com/openframeworks/openFrameworks/issues/2807

NORMAL=$(tput sgr0)
RED=$(tput setaf 1)
GREEN=$(tput setaf 2)

wget   https://github.com/openframeworks/openFrameworks/archive/$BRANCH.zip
unzip  $BRANCH.zip
rm     $BRANCH.zip

cd     openFrameworks-*

if patch -p1 < ../openFrameworks.patch; then
       echo "${GREEN}openFrameworks patched successfully.${NORMAL}"
else
       echo "${RED}Error: openFrameworks was not patched.${NORMAL}"
fi

cd     ..

mv     openFrameworks-*/libs/openFrameworks .

rm -rf openFrameworks/.settings
rm     openFrameworks/.project
rm     openFrameworks/.cproject

TESS=Dependencies/Libs/tess2
rm -rf $TESS
mkdir  $TESS
mv     openFrameworks-*/libs/tess2/include $TESS
mv     openFrameworks-*/libs/tess2/Sources $TESS

KISS=Dependencies/Libs/kiss
rm -rf $KISS
mkdir  $KISS
mv     openFrameworks-*/libs/kiss/include  $KISS
mv     openFrameworks-*/libs/kiss/src      $KISS

rm -rf openFrameworks-*

git    clone http://github.com/glfw/glfw.git Dependencies/Libs/glfw
cd     Dependencies/Libs/glfw
git    checkout 7f4e947447

cd     ../../..

git    clone http://github.com/pocoproject/poco.git Dependencies/Libs/poco
cd     Dependencies/Libs/poco
git    checkout 4923172241

patch -p1 < ../../poco.patch

cd     ../../..

