#!/bin/bash

OF_BRANCH=5f79889
GLFW_BRANCH=0a6cb34
POCO_BRANCH=814baaf

OF_REPO=https://github.com/openframeworks/openFrameworks/archive/$OF_BRANCH.zip
GLFW_REPO=https://github.com/arturoc/glfw/archive/$GLFW_BRANCH.zip
POCO_REPO=https://github.com/pocoproject/poco/archive/$POCO_BRANCH.zip
