#!/bin/bash

# Compiles OF and its dependencies

cd `dirname $(readlink -f $0)`

cd Scripts

./compile_dep_linux-64
./compile_dep_mingw-64
./compile_of_linux-64_release
./compile_of_mingw-64_release
./compile_of_linux-64_debug
