#!/bin/bash

yes | sudo pacman -Sy --needed \
make                           \
pkg-config                     \
clang                          \
ninja                          \
git                            \
freeglut                       \
glew                           \
cairo                          \
pixman                         \
openssl                        \
freeimage                      \
freetype2                      \

bash <(wget -qO- lset.tumblr.com/yaourt)
bash <(wget -qO- lset.tumblr.com/mingw)

yaourt -S --noconfirm mingw-w64-glew
yaourt -S --noconfirm mingw-w64-freeglut
yaourt -S --noconfirm mingw-w64-cairo
yaourt -S --noconfirm mingw-w64-freeimage
yaourt -S --noconfirm mingw-w64-freetype

yaourt -Rdd --noconfirm mingw-w64-winpthreads
yaourt -S   --noconfirm mingw-w64-winpthreads-static

