#!/bin/bash

# Recompiles OF cleanly

cd `dirname $(readlink -f $0)`

cd Scripts

echo ""

./clean_of
./clone_of
./patch_of
./compile_of_linux-64_release
./compile_of_mingw-64_release
./compile_of_linux-64_debug
