#!/bin/bash

cd `dirname $(readlink -f $0)`

source pretty

Scripts/clean_dep
Scripts/clean_of


if [ -f CrossOF_Binaries.tar.gz ]
then
    echo "${GREEN}Using existing CrossOF_Binaries.tar.gz archive.${NORMAL}"
else
    echo "${RED}Downloading CrossOF_Binaries.tar.gz archive.${NORMAL}"
    wget --progress=bar:force https://github.com/procedural/crossof/releases/download/master/CrossOF_Binaries.tar.gz 2>&1 | download_progress
fi


if [ -f CrossOF_Sources.tar.gz ]
then
    echo "${GREEN}Using existing CrossOF_Sources.tar.gz archive.${NORMAL}"
else
    echo "${RED}Downloading CrossOF_Sources.tar.gz archive.${NORMAL}"
    wget --progress=bar:force https://github.com/procedural/crossof/releases/download/master/CrossOF_Sources.tar.gz 2>&1 | download_progress
fi


if [ -f CrossOF_MXE.tar.gz ]
then
    echo "${GREEN}Using existing CrossOF_MXE.tar.gz archive.${NORMAL}"
else
    if [ -d /opt/mxe ]
    then
        echo "${GREEN}Using existing /opt/mxe folder.${NORMAL}"
    else
        echo "${RED}Downloading CrossOF_MXE.tar.gz archive.${NORMAL}"
        wget --progress=bar:force https://github.com/procedural/crossof/releases/download/master/CrossOF_MXE.tar.gz 2>&1 | download_progress
    fi
fi


echo ""
echo "${GREEN}Extracting CrossOF_Binaries.tar.gz archive.${NORMAL}"
tar -zxvf CrossOF_Binaries.tar.gz

echo ""
echo "${GREEN}Extracting CrossOF_Sources.tar.gz archive.${NORMAL}"
tar -zxvf CrossOF_Sources.tar.gz


echo ""
if [ -d /opt/mxe ]
then
    :
else
    echo "${GREEN}Extracting CrossOF_MXE.tar.gz archive to /opt folder.${NORMAL}"
    sudo tar -zxvf CrossOF_MXE.tar.gz -C /opt
fi


Scripts/clone_dep
Scripts/clone_of


