#!/bin/bash

cd `dirname $(readlink -f $0)`

DEPS=`pwd`

mkdir -p Compiled/linux-64/Debug/fontconfig
cd       Compiled/linux-64/Debug/fontconfig

cmake -DCMAKE_C_FLAGS="-g -fPIC -fcolor-diagnostics" \
      -DCMAKE_C_COMPILER=clang \
      -G Ninja $DEPS/Libs/fontconfig
ninja
