#!/bin/bash

cd `dirname $(readlink -f $0)`

DEPS=`pwd`

cd    Libs/freeimage

mkdir -p compiled/mingw-64
cd       compiled/mingw-64

cmake -DCMAKE_TOOLCHAIN_FILE=/opt/mxe/usr/x86_64-w64-mingw32.static/share/cmake/mxe-conf.cmake \
      -G Ninja \
      ../..
ninja

cp    lib/libfreeimage.a $DEPS/Compiled/mingw-64
cp    lib/libopenjpeg.a  $DEPS/Compiled/mingw-64
cp    lib/libopenexr.a   $DEPS/Compiled/mingw-64
cp    lib/librawlite.a   $DEPS/Compiled/mingw-64
cp    lib/libtiff.a      $DEPS/Compiled/mingw-64
cp    lib/libjpeg.a      $DEPS/Compiled/mingw-64
cp    lib/libpng.a       $DEPS/Compiled/mingw-64
