#!/bin/bash

cd `dirname $(readlink -f $0)`

DEPS=`pwd`

cd    Libs/freeimage

mkdir -p compiled/linux-64
cd       compiled/linux-64

cmake -DCMAKE_CXX_COMPILER=clang++ \
      -DCMAKE_C_COMPILER=clang     \
      -G Ninja                     \
      ../..
ninja

cp                lib/libfreeimage.a  $DEPS/Compiled/linux-64
cp        LibJPEG/lib/libjpeg.a       $DEPS/Compiled/linux-64
cp    LibOpenJPEG/lib/libopenjpeg.a   $DEPS/Compiled/linux-64
cp         LibPNG/lib/libpng.a        $DEPS/Compiled/linux-64
cp     LibRawLite/lib/librawlite.a    $DEPS/Compiled/linux-64
cp       LibTIFF4/lib/libtiff.a       $DEPS/Compiled/linux-64
cp        OpenEXR/lib/libopenexr.a    $DEPS/Compiled/linux-64
