#!/bin/bash

cd `dirname $(readlink -f $0)`

DEPS=`pwd`

mkdir -p Compiled/linux-64/freeimage
cd       Compiled/linux-64/freeimage

cmake -DCMAKE_C_COMPILER=clang     \
      -DCMAKE_CXX_COMPILER=clang++ \
      -G Ninja $DEPS/Libs/freeimage
ninja
