#!/bin/bash

cd `dirname $(readlink -f $0)`

DEPS=`pwd`

mkdir -p Compiled/linux-64/Release/glew
cd       Compiled/linux-64/Release/glew

cmake -DCMAKE_C_FLAGS="-w -O3"      \
      -Dglew-cmake_BUILD_SHARED=OFF \
      -DONLY_LIBS=ON                \
      -DCMAKE_C_COMPILER=clang      \
      -G Ninja $DEPS/Libs/glew
ninja
