#!/bin/bash

cd `dirname $(readlink -f $0)`

DEPS=`pwd`

cd    Libs/glew

mkdir -p compiled/mingw-64
cd       compiled/mingw-64

cmake -DCMAKE_TOOLCHAIN_FILE=/opt/mxe/usr/x86_64-w64-mingw32.static/share/cmake/mxe-conf.cmake \
      -G Ninja \
      ../..
ninja

cp    lib/libglew.a $DEPS/Compiled/mingw-64

