#!/bin/bash

cd `dirname $(readlink -f $0)`

DEPS=`pwd`

mkdir -p Compiled/mingw-64/glew
cd       Compiled/mingw-64/glew

cmake -DCMAKE_TOOLCHAIN_FILE=/opt/mxe/usr/x86_64-w64-mingw32.static/share/cmake/mxe-conf.cmake \
      -Dglew-cmake_BUILD_SHARED=OFF \
      -DONLY_LIBS=ON                \
      -G Ninja $DEPS/Libs/glew
ninja
