#!/bin/bash

cd `dirname $(readlink -f $0)`

DEPS=`pwd`

mkdir -p Compiled/linux-64/glew
cd       Compiled/linux-64/glew

cmake -Dglew-cmake_BUILD_SHARED=OFF \
      -DONLY_LIBS=ON                \
      -DCMAKE_C_FLAGS="-fPIC"       \
      -DCMAKE_C_COMPILER=clang      \
      -G Ninja $DEPS/Libs/glew
ninja
