#!/bin/bash

cd `dirname $(readlink -f $0)`

DIR=`pwd`

cd    Libs/glfw

mkdir -p compiled/mingw-64
cd       compiled/mingw-64

cmake -G Ninja                  \
      -DCMAKE_TOOLCHAIN_FILE=/opt/mxe/usr/x86_64-w64-mingw32.static/share/cmake/mxe-conf.cmake \
      -DGLFW_BUILD_TESTS=OFF    \
      -DGLFW_BUILD_EXAMPLES=OFF \
      ../..
ninja

cp    src/libglfw3.a $DIR/Compiled/mingw-64

