#!/bin/bash

FILE=$(readlink -f $0)
DIR=`dirname $FILE`

cd    $DIR

cd    Libs/glfw
mkdir compiled

mkdir compiled/linux-64
cd    compiled/linux-64

cmake -G Ninja                 \
      -DCMAKE_C_COMPILER=clang \
      ../..
ninja

cp    src/libglfw3.a $DIR/Compiled/linux-64

