#!/bin/bash

cd `dirname $(readlink -f $0)`

DEPS=`pwd`

mkdir -p Compiled/linux-64/Release/glfw
cd       Compiled/linux-64/Release/glfw

cmake -DCMAKE_C_FLAGS="-w -O3"  \
      -DGLFW_BUILD_TESTS=OFF    \
      -DGLFW_BUILD_EXAMPLES=OFF \
      -DCMAKE_C_COMPILER=clang  \
      -G Ninja $DEPS/Libs/glfw
ninja
