#!/bin/bash

cd `dirname $(readlink -f $0)`

DEPS=`pwd`

mkdir -p Compiled/linux-64/Debug/glfw
cd       Compiled/linux-64/Debug/glfw

cmake -DCMAKE_C_FLAGS="-g -fPIC -fcolor-diagnostics"   \
      -DGLFW_BUILD_TESTS=OFF    \
      -DGLFW_BUILD_EXAMPLES=OFF \
      -DCMAKE_C_COMPILER=clang  \
      -G Ninja $DEPS/Libs/glfw
ninja
