#!/bin/bash

cd `dirname $(readlink -f $0)`

DEPS=`pwd`

cd    Libs/glfw

mkdir -p compiled/linux-64
cd       compiled/linux-64

cmake -DCMAKE_C_COMPILER=clang  \
      -DGLFW_BUILD_TESTS=OFF    \
      -DGLFW_BUILD_EXAMPLES=OFF \
      -G Ninja                  \
      ../..
ninja

cp    src/libglfw3.a $DEPS/Compiled/linux-64

