#!/bin/bash

FILE=$(readlink -f $0)
DIR=`dirname $FILE`

cd    $DIR

cd    Libs/kiss
mkdir compiled

mkdir compiled/mingw-64
cd    compiled/mingw-64

MINGW=/opt/mxe/usr

$MINGW/bin/x86_64-w64-mingw32.static-gcc   -I../../include -c ../../src/kiss_fft.c
$MINGW/bin/x86_64-w64-mingw32.static-gcc   -I../../include -c ../../src/kiss_fftr.c
$MINGW/bin/x86_64-w64-mingw32.static-ar cr libkiss.a kiss_fft.o kiss_fftr.o

cp    libkiss.a $DIR/Compiled/mingw-64

