#!/bin/bash

cd `dirname $(readlink -f $0)`

DIR=`pwd`

cd    Libs/kiss

mkdir -p compiled/linux-64
cd       compiled/linux-64

clang -I../../include -c ../../src/kiss_fft.c
clang -I../../include -c ../../src/kiss_fftr.c
ar cr libkiss.a kiss_fft.o kiss_fftr.o

cp    libkiss.a $DIR/Compiled/linux-64

