#!/bin/bash

cd `dirname $(readlink -f $0)`

DEPS=`pwd`

cd    Libs/kiss

KISS=`pwd`

mkdir -p compiled/linux-64
cd       compiled/linux-64

clang -I$KISS/include -c $KISS/src/kiss_fft.c
clang -I$KISS/include -c $KISS/src/kiss_fftr.c
ar cr libkiss.a kiss_fft.o kiss_fftr.o

cp    libkiss.a $DEPS/Compiled/linux-64

