#!/bin/bash

cd `dirname $(readlink -f $0)`

DEPS=`pwd`

mkdir -p Compiled/linux-64/Debug/kiss
cd       Compiled/linux-64/Debug/kiss

clang -g -fPIC -I$DEPS/Libs/kiss/include -c $DEPS/Libs/kiss/src/kiss_fft.c
clang -g -fPIC -I$DEPS/Libs/kiss/include -c $DEPS/Libs/kiss/src/kiss_fftr.c
ar cr libkiss.a kiss_fft.o kiss_fftr.o
