#!/bin/bash

cd `dirname $(readlink -f $0)`

DEPS=`pwd`

mkdir -p Compiled/mingw-64/Release/poco
cd       Compiled/mingw-64/Release/poco

export OPENSSL_ROOT_DIR=/opt/mxe/usr

cmake -DCMAKE_TOOLCHAIN_FILE=/opt/mxe/usr/x86_64-w64-mingw32.static/share/cmake/mxe-conf.cmake \
      -DPOCO_STATIC=ON         \
      -DCMAKE_BUILD_TYPE=None  \
      -DCMAKE_C_FLAGS="-w -O3" \
      -DCMAKE_CXX_FLAGS="-w -O3 -std=c++11 -fpermissive -DPOCO_ENABLE_CPP11 -DPCRE_STATIC -DPOCO_NO_FPENVIRONMENT -DPOCO_NO_AUTOMATIC_LIB_INIT -DPOCO_UTIL_NO_JSONCONFIGURATION" \
      -G Ninja $DEPS/Libs/poco
ninja
