#!/bin/bash

FILE=$(readlink -f $0)
DIR=`dirname $FILE`

cd     $DIR

cp     pocomsg.h Libs/poco/Foundation/src/pocomsg.h
cp     pocomsg.h Libs/poco/Foundation/include/Poco/pocomsg.h

cd     Libs/poco

mkdir -p compiled/mingw-64
cd       compiled/mingw-64

MINGW=/opt/mxe/usr

export OPENSSL_ROOT_DIR=$MINGW

cmake  -G Ninja                \
       -DCMAKE_TOOLCHAIN_FILE=/opt/mxe/usr/x86_64-w64-mingw32.static/share/cmake/mxe-conf.cmake \
       -DPOCO_STATIC=ON        \
       -DCMAKE_BUILD_TYPE=None \
       -DCMAKE_CXX_FLAGS="-O3 -std=c++11 -fpermissive -DPOCO_ENABLE_CPP11 -DPCRE_STATIC -DPOCO_NO_FPENVIRONMENT -DPOCO_NO_AUTOMATIC_LIB_INIT -DPOCO_UTIL_NO_JSONCONFIGURATION" \
       ../..
ninja

cd     lib

cp     libPocoFoundation.a $DIR/Compiled/mingw-64
cp     libPocoXML.a        $DIR/Compiled/mingw-64
cp     libPocoUtil.a       $DIR/Compiled/mingw-64
cp     libPocoNet.a        $DIR/Compiled/mingw-64
cp     libPocoCrypto.a     $DIR/Compiled/mingw-64
cp     libPocoNetSSL.a     $DIR/Compiled/mingw-64
cp     libPocoZip.a        $DIR/Compiled/mingw-64

