#!/bin/bash

cd `dirname $(readlink -f $0)`

DEPS=`pwd`

cd    Libs/tess2

TESS=`pwd`

mkdir -p compiled/mingw-64
cd       compiled/mingw-64

/opt/mxe/usr/bin/x86_64-w64-mingw32.static-gcc   -I$TESS/include -c $TESS/Sources/bucketalloc.c
/opt/mxe/usr/bin/x86_64-w64-mingw32.static-gcc   -I$TESS/include -c $TESS/Sources/dict.c
/opt/mxe/usr/bin/x86_64-w64-mingw32.static-gcc   -I$TESS/include -c $TESS/Sources/geom.c
/opt/mxe/usr/bin/x86_64-w64-mingw32.static-gcc   -I$TESS/include -c $TESS/Sources/mesh.c
/opt/mxe/usr/bin/x86_64-w64-mingw32.static-gcc   -I$TESS/include -c $TESS/Sources/priorityq.c
/opt/mxe/usr/bin/x86_64-w64-mingw32.static-gcc   -I$TESS/include -c $TESS/Sources/sweep.c
/opt/mxe/usr/bin/x86_64-w64-mingw32.static-gcc   -I$TESS/include -c $TESS/Sources/tess.c
/opt/mxe/usr/bin/x86_64-w64-mingw32.static-ar cr libtess2.a bucketalloc.o dict.o geom.o mesh.o priorityq.o sweep.o tess.o

cp    libtess2.a $DEPS/Compiled/mingw-64

