#!/bin/bash

cd `dirname $(readlink -f $0)`

DIR=`pwd`

cd     Libs/tess2

mkdir -p compiled/linux-64
cd       compiled/linux-64

clang  -I../../include -c ../../Sources/bucketalloc.c
clang  -I../../include -c ../../Sources/dict.c
clang  -I../../include -c ../../Sources/geom.c
clang  -I../../include -c ../../Sources/mesh.c
clang  -I../../include -c ../../Sources/priorityq.c
clang  -I../../include -c ../../Sources/sweep.c
clang  -I../../include -c ../../Sources/tess.c
ar cr  libtess2.a bucketalloc.o dict.o geom.o mesh.o priorityq.o sweep.o tess.o

cp     libtess2.a $DIR/Compiled/linux-64

