#!/bin/bash

cd `dirname $(readlink -f $0)`

DEPS=`pwd`

mkdir -p Compiled/mingw-64/Release/tess2
cd       Compiled/mingw-64/Release/tess2

/opt/mxe/usr/bin/x86_64-w64-mingw32.static-gcc -I$DEPS/Libs/tess2/include -c $DEPS/Libs/tess2/Sources/bucketalloc.c
/opt/mxe/usr/bin/x86_64-w64-mingw32.static-gcc -I$DEPS/Libs/tess2/include -c $DEPS/Libs/tess2/Sources/dict.c
/opt/mxe/usr/bin/x86_64-w64-mingw32.static-gcc -I$DEPS/Libs/tess2/include -c $DEPS/Libs/tess2/Sources/geom.c
/opt/mxe/usr/bin/x86_64-w64-mingw32.static-gcc -I$DEPS/Libs/tess2/include -c $DEPS/Libs/tess2/Sources/mesh.c
/opt/mxe/usr/bin/x86_64-w64-mingw32.static-gcc -I$DEPS/Libs/tess2/include -c $DEPS/Libs/tess2/Sources/priorityq.c
/opt/mxe/usr/bin/x86_64-w64-mingw32.static-gcc -I$DEPS/Libs/tess2/include -c $DEPS/Libs/tess2/Sources/sweep.c
/opt/mxe/usr/bin/x86_64-w64-mingw32.static-gcc -I$DEPS/Libs/tess2/include -c $DEPS/Libs/tess2/Sources/tess.c
/opt/mxe/usr/bin/x86_64-w64-mingw32.static-ar cr libtess2.a bucketalloc.o dict.o geom.o mesh.o priorityq.o sweep.o tess.o
