#!/bin/bash

FILE=$(readlink -f $0)
DIR=`dirname $FILE`

cd    $DIR

cd    Libs/tess2

mkdir -p compiled/mingw-64
cd       compiled/mingw-64

MINGW=/opt/mxe/usr

$MINGW/bin/x86_64-w64-mingw32.static-gcc   -I../../include -c ../../Sources/bucketalloc.c
$MINGW/bin/x86_64-w64-mingw32.static-gcc   -I../../include -c ../../Sources/dict.c
$MINGW/bin/x86_64-w64-mingw32.static-gcc   -I../../include -c ../../Sources/geom.c
$MINGW/bin/x86_64-w64-mingw32.static-gcc   -I../../include -c ../../Sources/mesh.c
$MINGW/bin/x86_64-w64-mingw32.static-gcc   -I../../include -c ../../Sources/priorityq.c
$MINGW/bin/x86_64-w64-mingw32.static-gcc   -I../../include -c ../../Sources/sweep.c
$MINGW/bin/x86_64-w64-mingw32.static-gcc   -I../../include -c ../../Sources/tess.c
$MINGW/bin/x86_64-w64-mingw32.static-ar cr libtess2.a bucketalloc.o dict.o geom.o mesh.o priorityq.o sweep.o tess.o

cp    libtess2.a $DIR/Compiled/mingw-64

