#!/bin/bash

cd `dirname $(readlink -f $0)`

DEPS=`pwd`

mkdir -p Compiled/linux-64/Release/zlib
cd       Compiled/linux-64/Release/zlib

cmake -DCMAKE_C_FLAGS="-w -O3"     \
      -DCMAKE_CXX_FLAGS="-w -O3"   \
      -DCMAKE_C_COMPILER=clang     \
      -DCMAKE_CXX_COMPILER=clang++ \
      -G Ninja $DEPS/Libs/zlib
ninja
