#!/bin/bash

cd `dirname $(readlink -f $0)`

DEPS=`pwd`

mkdir -p Compiled/linux-64/zlib
cd       Compiled/linux-64/zlib

cmake -DCMAKE_C_FLAGS="-fPIC"      \
      -DCMAKE_CXX_FLAGS="-fPIC"    \
      -DCMAKE_C_COMPILER=clang     \
      -DCMAKE_CXX_COMPILER=clang++ \
      -G Ninja $DEPS/Libs/zlib
ninja
