#!/bin/bash

cd `dirname $(readlink -f $0)`
cd ..

source pretty

echo "${GREEN}Installing Arch Linux dependencies.${NORMAL}"

yes | sudo pacman -Syu

yes | sudo pacman -Sy --needed \
git                            \
make                           \
pkg-config                     \
xorg-server-devel              \
libxcursor                     \
libxrandr                      \
libxi                          \
clang                          \
clang-analyzer                 \
cmake                          \
ninja                          \
openssl                        \
cairo                          \
freeglut                       \
freetype2                      \
fontconfig

yes | sudo pacman -Sy --needed \
    autoconf automake bash bison bzip2 cmake flex gettext \
    git gcc gperf intltool libffi libtool openssl wget xz \
    coreutils patch pkg-config perl perl-xml-parser scons \
    sed make unzip gettext ruby

echo ""
if [ ! -d /opt/mxe ]
then
    echo "${RED}Setting up /opt/mxe folder.${NORMAL}"
    sudo git clone https://github.com/mxe/mxe.git /opt/mxe
else
    echo "${GREEN}Using existing /opt/mxe folder.${NORMAL}"
fi

cd /opt/mxe

sudo make MXE_TARGETS=x86_64-w64-mingw32.static \
mingw-w64   \
winpthreads \
openssl     \
cairo       \
freeglut    \
freetype

sudo ln -s /opt/mxe/usr/x86_64-w64-mingw32.static/share/cmake/mxe-conf.cmake /opt/mxe/mingw.cmake 2> /dev/null

