#!/bin/bash

cd `dirname $(readlink -f $0)`
cd ..

source pretty

echo "${GREEN}Installing Ubuntu dependencies.${NORMAL}"

sudo apt-get update
sudo apt-get -y upgrade

sudo apt-get -y install \
xorg-dev                \
libgtk2.0-dev           \
libudev-dev             \
llvm                    \
clang                   \
cmake                   \
ninja-build             \
libcairo2-dev           \
libssl-dev              \
freeglut3-dev           \
libfreetype6-dev

sudo apt-get -y install \
    autoconf automake bash bison bzip2 cmake flex gettext \
    git g++ gperf intltool libffi-dev libtool libltdl-dev \
    libssl-dev libxml-parser-perl make openssl patch perl \
    pkg-config python ruby scons sed unzip wget autopoint \
    xz-utils

echo ""
if [ ! -d /opt/mxe ]
then
    echo "${RED}Setting up /opt/mxe folder.${NORMAL}"
    sudo git clone https://github.com/mxe/mxe.git /opt/mxe
else
    echo "${GREEN}Using existing /opt/mxe folder.${NORMAL}"
fi

cd /opt/mxe

sudo make MXE_TARGETS=x86_64-w64-mingw32.static \
mingw-w64   \
winpthreads \
cairo       \
openssl     \
freeglut    \
freetype

sudo ln -s /usr/bin/llvm-symbolizer* /usr/bin/llvm-symbolizer 2> /dev/null
sudo ln -s /opt/mxe/usr/x86_64-w64-mingw32.static/share/cmake/mxe-conf.cmake /opt/mxe/mingw.cmake 2> /dev/null

