#!/bin/bash

cd `dirname $(readlink -f $0)`
cd ..

function clu() {
    # $1 Name
    # $2 Folder
    # $3 Branch hash
    # $4 Repository url
    rm -rf Dependencies/Archive/$2/$2-*
    rm -rf Dependencies/Libs/$2
}

source clu
