#!/bin/bash

FILE=$(readlink -f $0)
DIR=`dirname $FILE`

cd $DIR
cd ..

rm -rf Dependencies/Archive/glfw/glfw-*
rm -rf Dependencies/Archive/poco/poco-*

rm -rf Dependencies/Libs/glfw
rm -rf Dependencies/Libs/poco
