#!/bin/bash

cd `dirname $(readlink -f $0)`
cd ..

rm -rf Dependencies/Archive/glfw/glfw-*
rm -rf Dependencies/Archive/poco/poco-*

rm -rf Dependencies/Libs/glfw
rm -rf Dependencies/Libs/poco
rm -rf Dependencies/Libs/freeimage
