#!/bin/bash

cd `dirname $(readlink -f $0)`
cd ..

source pretty

echo ""
echo "${CYAN}Cleaning openFrameworks${NORMAL}"

rm -rf openFrameworks
rm -rf openFrameworks-*

rm -rf Dependencies/Libs/kiss
rm -rf Dependencies/Libs/tess2
