#!/bin/bash

cd `dirname $(readlink -f $0)`
cd ..

OF=`pwd`

source commits
source pretty

echo   ""
if [ ! -f $OF/Archive/$OF_BRANCH.zip ]
then
       echo "${RED}Downloading $OF_BRANCH.zip archive for openFrameworks.${NORMAL}"
       cd $OF/Archive
       wget --progress=bar:force $OF_REPO 2>&1 | download_progress
       cd ..
else
       echo "${GREEN}Using existing $OF_BRANCH.zip archive for openFrameworks.${NORMAL}"
fi
unzip  -q $OF/Archive/$OF_BRANCH.zip
mv     openFrameworks-*/libs/openFrameworks .

rm -rf Dependencies/Libs/tess2
mkdir  Dependencies/Libs/tess2
mv     openFrameworks-*/libs/tess2/include Dependencies/Libs/tess2
mv     openFrameworks-*/libs/tess2/Sources Dependencies/Libs/tess2

rm -rf Dependencies/Libs/kiss
mkdir  Dependencies/Libs/kiss
mv     openFrameworks-*/libs/kiss/include  Dependencies/Libs/kiss
mv     openFrameworks-*/libs/kiss/src      Dependencies/Libs/kiss

rm -rf openFrameworks-*

