#!/bin/bash

download_progress()
{
    local flag=false c count cr=$'\r' nl=$'\n'
    while IFS='' read -d '' -rn 1 c
    do
        if $flag
        then
            printf '%c' "$c"
        else
            if [[ $c != $cr && $c != $nl ]]
            then
                count=0
            else
                ((count++))
                if ((count > 1))
                then
                    flag=true
                fi
            fi
        fi
    done
}

NORMAL=$(tput sgr0)
RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
CYAN=$(tput setaf 6)



FILE=$(readlink -f $0)
DIR=`dirname $FILE`

cd $DIR
cd ..

source commits



echo   ""
if [ -f $OF_BRANCH.zip ]
then
       echo "${GREEN}Using existing $OF_BRANCH.zip archive for openFrameworks.${NORMAL}"
else
       echo "${RED}Downloading $OF_BRANCH.zip archive for openFrameworks.${NORMAL}"
       wget --progress=bar:force $OF_REPO 2>&1 | download_progress
fi

unzip  -q $OF_BRANCH.zip

mv     openFrameworks-*/libs/openFrameworks .

rm -rf openFrameworks/.settings
rm     openFrameworks/.project
rm     openFrameworks/.cproject


Scripts/patch_of


TESS=Dependencies/Libs/tess2
rm -rf $TESS
mkdir  $TESS
mv     openFrameworks-*/libs/tess2/include $TESS
mv     openFrameworks-*/libs/tess2/Sources $TESS

KISS=Dependencies/Libs/kiss
rm -rf $KISS
mkdir  $KISS
mv     openFrameworks-*/libs/kiss/include  $KISS
mv     openFrameworks-*/libs/kiss/src      $KISS

rm -rf openFrameworks-*

