#!/bin/bash

cd `dirname $(readlink -f $0)`
cd ..

source commits
source pretty

OF=`pwd`
DEPS=$OF/Dependencies

echo ""

function ccd() {
    # $1 Name
    # $2 Folder
    # $3 Branch hash
    # $4 Repository url
    mkdir -p $DEPS/Archive/$2
    cd $DEPS/Archive/$2
    if [ ! -f $3.zip ]
    then
       echo "${RED}Downloading $3.zip archive for $1.${NORMAL}"
       wget --progress=bar:force $4 2>&1 | download_progress
    else
       echo "${GREEN}Using existing $3.zip archive for $1.${NORMAL}"
    fi
    unzip -q $3.zip
    mv     $2-* $DEPS/Libs/$2
    rm -rf $2-*
}

source ccd

# POCO patch
cd     $DEPS/Libs/poco
echo   ""
echo   ${CYAN}poco_mingw_fixes.patch${NORMAL}
patch  -p1 < $OF/Patches/poco_mingw_fixes.patch
echo   ""
echo   ${CYAN}poco_cmake_changes.patch${NORMAL}
patch  -p1 < $OF/Patches/poco_cmake_changes.patch
echo   ""
echo   ${CYAN}poco_warning_fixes.patch${NORMAL}
patch  -p1 < $OF/Patches/poco_warning_fixes.patch

