#!/bin/bash

GLFW_BRANCH=0a6cb34815
POCO_BRANCH=fb06f5b8aa

download_progress()
{
    local flag=false c count cr=$'\r' nl=$'\n'
    while IFS='' read -d '' -rn 1 c
    do
        if $flag
        then
            printf '%c' "$c"
        else
            if [[ $c != $cr && $c != $nl ]]
            then
                count=0
            else
                ((count++))
                if ((count > 1))
                then
                    flag=true
                fi
            fi
        fi
    done
}

NORMAL=$(tput sgr0)
RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
CYAN=$(tput setaf 6)



FILE=$(readlink -f $0)
DIR=`dirname $FILE`

cd $DIR
cd ..



cd     Dependencies/Archive/glfw

echo   ""
if [ -f $GLFW_BRANCH.zip ]
then
       echo "${GREEN}Using existing $GLFW_BRANCH.zip archive for GLFW.${NORMAL}"
else
       echo "${RED}Downloading $GLFW_BRANCH.zip archive for GLFW.${NORMAL}"
       wget --progress=bar:force https://github.com/arturoc/glfw/archive/$GLFW_BRANCH.zip 2>&1 | download_progress
fi

unzip -q $GLFW_BRANCH.zip

mv     glfw-* ../../Libs/glfw
rm -rf glfw-*

cd     ../../..



cd     Dependencies/Archive/poco

echo   ""
if [ -f $POCO_BRANCH.zip ]
then
       echo "${GREEN}Using existing $POCO_BRANCH.zip archive for POCO.${NORMAL}"
else
       echo "${RED}Downloading $POCO_BRANCH.zip archive for POCO.${NORMAL}"
       wget --progress=bar:force https://github.com/pocoproject/poco/archive/$POCO_BRANCH.zip 2>&1 | download_progress
fi

unzip  -q $POCO_BRANCH.zip

mv     poco-* ../../Libs/poco
rm -rf poco-*

cd     ../../..

cd     Dependencies/Libs/poco

echo   ""
echo   ${CYAN}poco.patch${NORMAL}
patch  -p1 < ../../poco.patch

echo   ""
echo   ${CYAN}poco_cmake.patch${NORMAL}
patch  -p1 < ../../poco_cmake.patch

cd     ../../..

