#!/bin/bash

OF_BRANCH=3848dd7d53
GLFW_BRANCH=896d040c68
POCO_BRANCH=fb06f5b8aa

download_progress()
{
    local flag=false c count cr=$'\r' nl=$'\n'
    while IFS='' read -d '' -rn 1 c
    do
        if $flag
        then
            printf '%c' "$c"
        else
            if [[ $c != $cr && $c != $nl ]]
            then
                count=0
            else
                ((count++))
                if ((count > 1))
                then
                    flag=true
                fi
            fi
        fi
    done
}

NORMAL=$(tput sgr0)
RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
CYAN=$(tput setaf 6)



FILE=$(readlink -f $0)
DIR=`dirname $FILE`

cd $DIR
cd ..



echo   ""
if [ -f $OF_BRANCH.zip ]
then
       echo "${GREEN}Using existing $OF_BRANCH.zip archive for openFrameworks.${NORMAL}"
else
       echo "${RED}Downloading $OF_BRANCH.zip archive for openFrameworks.${NORMAL}"
       wget --progress=bar:force https://github.com/openframeworks/openFrameworks/archive/$OF_BRANCH.zip 2>&1 | download_progress
fi

unzip  -q $OF_BRANCH.zip

mv     openFrameworks-*/libs/openFrameworks .

rm -rf openFrameworks/.settings
rm     openFrameworks/.project
rm     openFrameworks/.cproject



echo   ""
echo   ${CYAN}of_mingw_fix.patch${NORMAL}
patch  -p1 < Patches/of_mingw_fix.patch

echo   ""
echo   ${CYAN}of_glew_include_path_fix.patch${NORMAL}
patch  -p1 < Patches/of_glew_include_path_fix.patch

echo   ""
echo   ${CYAN}of_scroll_feature.patch${NORMAL}
patch  -p1 < Patches/of_scroll_feature.patch

echo   ""
echo   ${CYAN}of_audio_video_disable.patch${NORMAL}
patch  -p1 < Patches/of_audio_video_disable.patch

echo   ""
echo   ${CYAN}of_clipboard_feature.patch${NORMAL}
patch  -p1 < Patches/of_clipboard_feature.patch

echo   ""
echo   ${CYAN}of_glfw_mismatch_fix.patch${NORMAL}
patch  -p1 < Patches/of_glfw_mismatch_fix.patch

echo   ""
echo   ${CYAN}of_compile_error_fix.patch${NORMAL}
patch  -p1 < Patches/of_compile_error_fix.patch



TESS=Dependencies/Libs/tess2
rm -rf $TESS
mkdir  $TESS
mv     openFrameworks-*/libs/tess2/include $TESS
mv     openFrameworks-*/libs/tess2/Sources $TESS

KISS=Dependencies/Libs/kiss
rm -rf $KISS
mkdir  $KISS
mv     openFrameworks-*/libs/kiss/include  $KISS
mv     openFrameworks-*/libs/kiss/src      $KISS

rm -rf openFrameworks-*



cd     Dependencies/Archive/glfw

echo   ""
if [ -f $GLFW_BRANCH.zip ]
then
       echo "${GREEN}Using existing $GLFW_BRANCH.zip archive for GLFW.${NORMAL}"
else
       echo "${RED}Downloading $GLFW_BRANCH.zip archive for GLFW.${NORMAL}"
       wget --progress=bar:force https://github.com/glfw/glfw/archive/$GLFW_BRANCH.zip 2>&1 | download_progress
fi

unzip -q $GLFW_BRANCH.zip

mv     glfw-* ../../Libs/glfw
rm -rf glfw-*

cd     ../../..



cd     Dependencies/Archive/poco

echo   ""
if [ -f $POCO_BRANCH.zip ]
then
       echo "${GREEN}Using existing $POCO_BRANCH.zip archive for POCO.${NORMAL}"
else
       echo "${RED}Downloading $POCO_BRANCH.zip archive for POCO.${NORMAL}"
       wget --progress=bar:force https://github.com/pocoproject/poco/archive/$POCO_BRANCH.zip 2>&1 | download_progress
fi

unzip  -q $POCO_BRANCH.zip

mv     poco-* ../../Libs/poco
rm -rf poco-*

cd     ../../..

cd     Dependencies/Libs/poco

echo   ""
echo   ${CYAN}poco.patch${NORMAL}
patch  -p1 < ../../poco.patch

cd     ../../..



