#!/bin/bash

cd `dirname $(readlink -f $0)`
cd ..

source commits
source pretty

cd Dependencies
DEPS=`pwd`
cd ..

function clone() {
    cd     $DEPS/Archive/$2
    echo   ""
    if [ ! -f $3.zip ]
    then
           echo "${RED}Downloading $3.zip archive for $1.${NORMAL}"
           wget --progress=bar:force $4 2>&1 | download_progress
    else
           echo "${GREEN}Using existing $3.zip archive for $1.${NORMAL}"
    fi
    unzip -q $3.zip
    mv     $2-* $DEPS/Libs/$2
    rm -rf $2-*
}

clone GLEW glew $GLEW_BRANCH $GLEW_REPO
clone GLFW glfw $GLFW_BRANCH $GLFW_REPO
clone POCO poco $POCO_BRANCH $POCO_REPO
clone FreeImage freeimage $FREEIMAGE_BRANCH $FREEIMAGE_REPO

# POCO patch
echo   ""
echo   "${CYAN}Copying pocomsg.h for POCO${NORMAL}"
cp     $DEPS/pocomsg.h $DEPS/Libs/poco/Foundation/src/pocomsg.h
cp     $DEPS/pocomsg.h $DEPS/Libs/poco/Foundation/include/Poco/pocomsg.h
cd     $DEPS/Libs/poco
echo   ""
echo   ${CYAN}poco.patch${NORMAL}
patch  -p1 < $DEPS/poco.patch
echo   ""
echo   ${CYAN}poco_cmake.patch${NORMAL}
patch  -p1 < $DEPS/poco_cmake.patch

