#!/bin/bash

cd `dirname $(readlink -f $0)`
cd ..

source pretty

cd Dependencies


echo ""
echo "${GREEN}Compiling KISS for Windows.${NORMAL}"

./kiss-mingw-64


echo ""
echo "${GREEN}Compiling TESS for Windows.${NORMAL}"

./tess2-mingw-64


echo ""
echo "${GREEN}Compiling GLEW for Windows.${NORMAL}"

./glew-mingw-64


echo ""
echo "${GREEN}Compiling GLFW for Windows.${NORMAL}"

./glfw-mingw-64


echo ""
echo "${GREEN}Compiling POCO for Windows.${NORMAL}"

./poco-mingw-64


echo ""
echo "${GREEN}Compiling FreeImage for Windows.${NORMAL}"

./freeimage-mingw-64

