#!/bin/bash

cd `dirname $(readlink -f $0)`
cd ..

source pretty

function ccd() {
    # $1 Name
    # $2 Folder
    # $3 Branch hash
    # $4 Repository url
    echo ""
    echo "${GREEN}Compiling Release version of $1 for Windows.${NORMAL}"
    Dependencies/$2_mingw-64_release
}

ccd Kiss kiss
ccd Tess2 tess2

source ccd
