#!/bin/bash

cd `dirname $(readlink -f $0)`
cd ..

source pretty

function clu() {
    # $1 Name
    # $2 Folder
    # $3 Branch hash
    # $4 Repository url
    echo ""
    echo "${GREEN}Compiling $1 for Linux.${NORMAL}"
    Dependencies/$2-linux-64
}

source clu
