#!/bin/bash

cd `dirname $(readlink -f $0)`
cd ..

source pretty

cd Dependencies


echo ""
echo "${GREEN}Compiling KISS for Linux.${NORMAL}"

./kiss-linux-64


echo ""
echo "${GREEN}Compiling TESS for Linux.${NORMAL}"

./tess2-linux-64


echo ""
echo "${GREEN}Compiling GLEW for Linux.${NORMAL}"

./glew-linux-64


echo ""
echo "${GREEN}Compiling GLFW for Linux.${NORMAL}"

./glfw-linux-64


echo ""
echo "${GREEN}Compiling POCO for Linux.${NORMAL}"

./poco-linux-64


echo ""
echo "${GREEN}Compiling FreeImage for Linux.${NORMAL}"

./freeimage-linux-64

