#!/bin/bash

cd `dirname $(readlink -f $0)`
cd ..

source pretty

OF=`pwd`
ANALYSE=$(dirname `readlink -f /usr/bin/scan-build`)

echo  ""
echo  "${GREEN}Compiling Debug version of openFrameworks for Linux.${NORMAL}"

mkdir -p $OF/Compiled/linux-64/Debug
cd       $OF/Compiled/linux-64/Debug

cmake $OF -G Ninja -DCMAKE_BUILD_TYPE=Debug \
 -DCMAKE_CXX_COMPILER=$ANALYSE/c++-analyzer \
   -DCMAKE_C_COMPILER=$ANALYSE/ccc-analyzer

scan-build -analyze-headers --use-cc=clang --use-c++=clang++ ninja

echo ""
echo "${GREEN}All done!${NORMAL}"

