#!/bin/bash

cd `dirname $(readlink -f $0)`
cd ..

source pretty

function ccd() {
    # $1 Name
    # $2 Folder
    # $3 Branch hash
    # $4 Repository url
    echo ""
    echo "${GREEN}Compiling $1 for Windows.${NORMAL}"
    Dependencies/$2-mingw-64
}

source ccd
