#!/bin/bash

cd `dirname $(readlink -f $0)`
cd ..

source pretty

OF=`pwd`


echo  ""
echo  "${GREEN}Compiling Release version of openFrameworks for Windows.${NORMAL}"

mkdir -p $OF/Compiled/mingw-64/Release_Build
cd       $OF/Compiled/mingw-64/Release_Build

cmake $OF -G Ninja -DCMAKE_TOOLCHAIN_FILE=/opt/mxe/usr/x86_64-w64-mingw32.static/share/cmake/mxe-conf.cmake
ninja

