#!/bin/bash

cd `dirname $(readlink -f $0)`
cd ..

source pretty

OF=`pwd`
ANALYSE=$(dirname `readlink -f /usr/bin/scan-build`)


echo  ""
echo  "${GREEN}Compiling Debug version of openFrameworks for Linux.${NORMAL}"

mkdir -p $OF/Compiled/linux-64/Debug-Build
cd       $OF/Compiled/linux-64/Debug-Build

cmake $OF -G Ninja -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=Debug \
-DCMAKE_CXX_COMPILER=$ANALYSE/c++-analyzer -DCMAKE_C_COMPILER=$ANALYSE/ccc-analyzer
scan-build -analyze-headers --use-cc=clang --use-c++=clang++ ninja | tee result.txt


echo  ""
echo  "${GREEN}Compiling Release version of openFrameworks for Linux.${NORMAL}"

mkdir -p $OF/Compiled/linux-64/Release-Build
cd       $OF/Compiled/linux-64/Release-Build

cmake $OF -G Ninja -DCMAKE_CXX_COMPILER=clang++
ninja


echo  ""
echo  "${GREEN}Compiling Release version of openFrameworks for Windows.${NORMAL}"

mkdir -p $OF/Compiled/mingw-64/Release-Build
cd       $OF/Compiled/mingw-64/Release-Build

cmake $OF -G Ninja -DCMAKE_TOOLCHAIN_FILE=/opt/mxe/mingw.cmake
ninja


echo  ""
echo  "${GREEN}All done!${NORMAL}"

