#!/bin/bash

cd `dirname $(readlink -f $0)`
cd ..

chmod +x ccd
chmod +x pack
chmod +x strip
chmod +x setup
chmod +x commits
chmod +x compile
chmod +x recompile_dep
chmod +x recompile_of

chmod +x Scripts/clean_dep
chmod +x Scripts/clean_of
chmod +x Scripts/clone_dep
chmod +x Scripts/clone_of
chmod +x Scripts/patch_of
chmod +x Scripts/compile_dep_linux-64
chmod +x Scripts/compile_dep_mingw-64
chmod +x Scripts/compile_of_linux-64_release
chmod +x Scripts/compile_of_mingw-64_release
chmod +x Scripts/compile_of_linux-64_debug

chmod +x Dependencies/kiss-linux-64
chmod +x Dependencies/kiss-mingw-64
chmod +x Dependencies/tess2-linux-64
chmod +x Dependencies/tess2-mingw-64
chmod +x Dependencies/zlib-linux-64
chmod +x Dependencies/zlib-mingw-64
chmod +x Dependencies/glew-linux-64
chmod +x Dependencies/glew-mingw-64
chmod +x Dependencies/glfw-linux-64
chmod +x Dependencies/glfw-mingw-64
chmod +x Dependencies/poco-linux-64
chmod +x Dependencies/poco-mingw-64
chmod +x Dependencies/openssl-linux-64
chmod +x Dependencies/openssl-mingw-64
chmod +x Dependencies/freeimage-linux-64
chmod +x Dependencies/freeimage-mingw-64
chmod +x Dependencies/fontconfig-linux-64
chmod +x Dependencies/fontconfig-mingw-64

chmod +x Install/archlinux_dependencies
chmod +x Install/fedora_dependencies
chmod +x Install/ubuntu_dependencies

chmod +x Template/Icon/icon.sh
chmod +x Template/sanitize.sh
chmod +x Template/analyze.sh

chmod +x Difference/generate

