#!/bin/bash

FILE=$(readlink -f $0)
DIR=`dirname $FILE`

cd $DIR
cd ..

chmod +x pack
chmod +x setup
chmod +x commits
chmod +x compile_on_arch
chmod +x compile_on_ubuntu
chmod +x recompile_dep
chmod +x recompile_of

chmod +x Scripts/clean_dep
chmod +x Scripts/clean_of
chmod +x Scripts/clone_dep
chmod +x Scripts/clone_of
chmod +x Scripts/patch_of
chmod +x Scripts/compile_dep
chmod +x Scripts/compile_of
chmod +x Scripts/Arch/install_dep
chmod +x Scripts/Ubuntu/install_dep

chmod +x Dependencies/glfw-linux-64
chmod +x Dependencies/glfw-mingw-64
chmod +x Dependencies/poco-linux-64
chmod +x Dependencies/poco-mingw-64
chmod +x Dependencies/kiss-linux-64
chmod +x Dependencies/kiss-mingw-64
chmod +x Dependencies/tess2-linux-64
chmod +x Dependencies/tess2-mingw-64
