#!/bin/bash

cd `dirname $(readlink -f $0)`
cd ..

chmod +x ccd
chmod +x pack
chmod +x strip
chmod +x setup
chmod +x commits
chmod +x prepare
chmod +x compile
chmod +x recompile_dep
chmod +x recompile_of

chmod +x Scripts/clean_dep
chmod +x Scripts/clean_of
chmod +x Scripts/clone_dep
chmod +x Scripts/clone_of
chmod +x Scripts/patch_of
chmod +x Scripts/compile_dep_linux-64
chmod +x Scripts/compile_dep_mingw-64
chmod +x Scripts/compile_of_linux-64_release
chmod +x Scripts/compile_of_mingw-64_release
chmod +x Scripts/compile_of_linux-64_debug

chmod +x Dependencies/kiss_linux-64_release
chmod +x Dependencies/kiss_linux-64_debug
chmod +x Dependencies/kiss_mingw-64_release
chmod +x Dependencies/tess2_linux-64_release
chmod +x Dependencies/tess2_linux-64_debug
chmod +x Dependencies/tess2_mingw-64_release
chmod +x Dependencies/glew_linux-64_release
chmod +x Dependencies/glew_linux-64_debug
chmod +x Dependencies/glew_mingw-64_release
chmod +x Dependencies/glfw_linux-64_release
chmod +x Dependencies/glfw_linux-64_debug
chmod +x Dependencies/glfw_mingw-64_release
chmod +x Dependencies/poco_linux-64_release
chmod +x Dependencies/poco_linux-64_debug
chmod +x Dependencies/poco_mingw-64_release
chmod +x Dependencies/freeimage_linux-64_release
chmod +x Dependencies/freeimage_linux-64_debug
chmod +x Dependencies/freeimage_mingw-64_release
chmod +x Dependencies/fontconfig_linux-64_release
chmod +x Dependencies/fontconfig_linux-64_debug
chmod +x Dependencies/fontconfig_mingw-64_release

chmod +x Install/archlinux_dependencies
chmod +x Install/fedora_dependencies
chmod +x Install/ubuntu_dependencies

chmod +x Template/Icon/icon.sh
chmod +x Template/sanitize.sh
chmod +x Template/analyze.sh

chmod +x Difference/generate

