#!/bin/bash

cd `dirname $(readlink -f $0)`
cd ..

source pretty

function apply() {
    echo  ""
    echo  ${CYAN}$1${NORMAL}
    patch -p1 < Patches/$1
}

apply of_audio_video_disable.patch
apply of_glfw_missing_include.patch
apply of_mingw_fix.patch
apply of_remove_deprecated_registers.patch
apply of_scroll_feature.patch
apply of_undo_commit_61932bb.patch

